/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Gustavo Rinaldi
 */
public class Pokedex extends javax.swing.JFrame {
    private Connection conn;
    /**
     * Creates new form Pokedex
     */
    public Pokedex(Connection conexao) {
        conn = conexao;
        initComponents();
        CarregarTipos();
        CarregarCores();
        CarregarFormatos();
        adicionarTabelaPokedex();
        txt_nomep.requestFocus(true);
    }
    // As 3 funções abaixo carregam as box de pesquisa
    // precisa colocar um limite no for baseado no número de opções e também colocar as opções no lugar de "?"
    // os nomes são auto explicativos
    public Pokedex(){};
    public void CarregarTipos(){
        tipo_box.removeAllItems();
        tipo_box.addItem("--");
        String query = "SELECT nome FROM tipos;";
        try{
            var cursor = conn.createStatement();
            var retorno = cursor.executeQuery(query);
            while (retorno.next()){
                tipo_box.addItem(retorno.getString("nome"));
            }
        } catch (SQLException ex){
            System.err.println(ex.getMessage());
        }
    }
    public void CarregarCores(){
        cor_box.removeAllItems();
        cor_box.addItem("--");
        String query = "SELECT nome FROM cor;";
        try{
            var cursor = conn.createStatement();
            var retorno = cursor.executeQuery(query);
            while (retorno.next()){
                cor_box.addItem(retorno.getString("nome"));
            }
        } catch (SQLException ex){
            System.err.println(ex.getMessage());
        }
    }
    public void CarregarFormatos(){
        formato_box.removeAllItems();
        formato_box.addItem("--");
        String query = "SELECT nome FROM shape;";
        try{
            var cursor = conn.createStatement();
            var retorno = cursor.executeQuery(query);
            while (retorno.next()){
                formato_box.addItem(retorno.getString("nome"));
            }
        } catch (SQLException ex){
            System.err.println(ex.getMessage());
        }
    }
    public void adicionarTabelaPokedex(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Numero", "Nome", "Tipo1", "Tipo2", "Cor", "Formato"}, 0);
        //TODO: fazer aqui. iterar por todo pokemon. nova view pra isso
        String query = "SELECT numero,nome,tipo_1,tipo_2,cor,formato FROM pokedex_tabela;";
        try{
            var cursor = conn.createStatement();
            var retorno = cursor.executeQuery(query);
            while (retorno.next()){
                Object linha[];
                /// adicionar nos {} todas as informações do objeto acima.
                if (retorno.getString("tipo_2").equals("none")){
                    linha = new Object[]{retorno.getString("numero"),retorno.getString("nome"),retorno.getString("tipo_1"),"",retorno.getString("cor"),retorno.getString("formato")};
                } else{
                    linha = new Object[]{retorno.getString("numero"),retorno.getString("nome"),retorno.getString("tipo_1"),retorno.getString("tipo_2"),retorno.getString("cor"),retorno.getString("formato")};
                }
                modelo.addRow(linha);
            }
        }catch (SQLException ex){
                System.err.println(ex.getMessage());
        }
        
        pokeTabela.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pokeTabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nomep = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        tipo_box = new javax.swing.JComboBox<>();
        cor_box = new javax.swing.JComboBox<>();
        formato_box = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bttn_buscaP = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        bttn_filtrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokedex");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pokemon_icon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(98, 7, 7));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("Voltar a tela inicial");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        pokeTabela.setBackground(new java.awt.Color(0, 0, 0));
        pokeTabela.setForeground(new java.awt.Color(255, 255, 255));
        pokeTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Nome", "Tipo 1", "Tipo 2", "Cor", "Formato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pokeTabela.setFocusable(false);
        pokeTabela.setShowGrid(true);
        pokeTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokeTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pokeTabela);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/snorlax_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pokedex");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        txt_nomep.setBackground(new java.awt.Color(153, 153, 153));
        txt_nomep.setForeground(new java.awt.Color(0, 0, 0));
        txt_nomep.setToolTipText("Qual nome do pokemon?");

        txt_numero.setBackground(new java.awt.Color(153, 153, 163));
        txt_numero.setForeground(new java.awt.Color(0, 0, 0));
        txt_numero.setToolTipText("Qual o número do pokemon?");

        tipo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cor_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        formato_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        formato_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formato_boxActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número: ");

        bttn_buscaP.setBackground(new java.awt.Color(204, 204, 204));
        bttn_buscaP.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        bttn_buscaP.setForeground(new java.awt.Color(0, 0, 0));
        bttn_buscaP.setText("Buscar");
        bttn_buscaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_buscaPActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/filtro_icon.png"))); // NOI18N
        jLabel5.setText("Filtros de Busca:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        bttn_filtrar.setBackground(new java.awt.Color(204, 204, 204));
        bttn_filtrar.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        bttn_filtrar.setForeground(new java.awt.Color(0, 0, 0));
        bttn_filtrar.setText("OK");
        bttn_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_filtrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo: ");

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cor: ");

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Formato:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nomep)
                                    .addComponent(txt_numero)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttn_buscaP)))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bttn_filtrar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tipo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cor_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(formato_box, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nomep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(bttn_buscaP)
                .addGap(75, 75, 75)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cor_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formato_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(bttn_filtrar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Inicial().setVisible(true);
        this.setVisible((false));
    }//GEN-LAST:event_backActionPerformed

    private void bttn_buscaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_buscaPActionPerformed
        if(txt_numero.getText().equals("")&& txt_nomep.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha alguma das duas buscas.", "Procurando por nada...", JOptionPane.ERROR_MESSAGE);
        }else if(txt_numero.getText().equals("")){
            // busca pelo nome o pokemon x
            new Pokemon(conn,txt_nomep.getText()).setVisible(true);
        }else{
            // busca pelo número o pokemon x
            try{
                String query = "SELECT nome FROM pokemons WHERE numero="+txt_numero.getText()+";";
                var statement = conn.createStatement();
                var result = statement.executeQuery(query);
                result.next();
                new Pokemon(conn,result.getString("nome")).setVisible(true);
            } catch (SQLException ex){
                System.err.println(ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_bttn_buscaPActionPerformed

    private void formato_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formato_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formato_boxActionPerformed

    private void bttn_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_filtrarActionPerformed
        // if todos iguais a "--" a pokedex tira o filtro
        if(tipo_box.getSelectedItem().equals("--") && cor_box.getSelectedItem().equals("--") && formato_box.getSelectedItem().equals("--")){
            adicionarTabelaPokedex();
        }else{
            DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Numero", "Nome", "Tipo1", "Tipo2", "Cor", "Formato"}, 0);
            String query = "SELECT numero,nome,tipo_1,tipo_2,cor,formato FROM pokedex_tabela WHERE";
            if (!(cor_box.getSelectedItem().equals("--"))){
                query = query + " cor = '"+cor_box.getSelectedItem()+"' AND";
            }
            
            if (!(tipo_box.getSelectedItem().equals("--"))){
                query = query + " (tipo_1 = '"+tipo_box.getSelectedItem()+"' OR tipo_2 = '"+tipo_box.getSelectedItem()+"') AND";
            } 
            
            if (!(formato_box.getSelectedItem().equals("--"))){
                query = query + " formato = '"+formato_box.getSelectedItem()+"' AND";
            } 
            query = query.substring(0, query.length()-4) + ";";
            try{
                var statement = conn.createStatement();
                var result = statement.executeQuery(query);
                while (result.next()){
                    Object linha[];
                    /// adicionar nos {} todas as informações do objeto acima.
                    if (result.getString("tipo_2").equals("none")){
                        linha = new Object[]{result.getString("numero"),result.getString("nome"),result.getString("tipo_1"),"",result.getString("cor"),result.getString("formato")};
                    } else{
                        linha = new Object[]{result.getString("numero"),result.getString("nome"),result.getString("tipo_1"),result.getString("tipo_2"),result.getString("cor"),result.getString("formato")};
                    }
                    modelo.addRow(linha);
                    }
            } catch (SQLException ex){
                System.err.println("filtrar deu ruim:"+ex.getMessage());
            }
            
            pokeTabela.setModel(modelo);
        }
    }//GEN-LAST:event_bttn_filtrarActionPerformed

    private void pokeTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokeTabelaMouseClicked
        // pega o numero do pokemon e abre a página do pokemon
        int i = pokeTabela.getSelectedRow();
        // a row precisa ser maior q 0 e menor ou igual ao numero de opções
        pokeTabela.getValueAt(i,1);
        new Pokemon(conn,pokeTabela.getValueAt(i,1).toString()).setVisible(true);
    }//GEN-LAST:event_pokeTabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton bttn_buscaP;
    private javax.swing.JButton bttn_filtrar;
    private javax.swing.JComboBox<String> cor_box;
    private javax.swing.JComboBox<String> formato_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pokeTabela;
    private javax.swing.JComboBox<String> tipo_box;
    private javax.swing.JTextField txt_nomep;
    private javax.swing.JTextField txt_numero;
    // End of variables declaration//GEN-END:variables
}
