/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JFrame;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Gustavo Rinaldi
 */
public class Pokemon extends javax.swing.JFrame {

    /**
     * Creates new form Pokemon
     */
    Connection conn;
    String nome;
    InputStream imagem;
    public Pokemon(Connection conexao, String nome_P) {
        conn = conexao;
        nome = nome_P;
        initComponents();
        //preencher com o banco de dados
        try{ 
            String tipo1 = "";
            String tipo2 = "";
            String evolutions = "";
            var statement = conn.createStatement();
            var query = "SELECT pokemons.sprite as imagem, pokemons.nome as nome, pokemons.numero as numero, pokemons.body_shape as formato, pokemons.color as cor, tipo1.nome_tipo as tipo_1, tipo2.nome_tipo as tipo_2, evolucao.nome as evo_nome FROM pokemons LEFT JOIN do_tipo as tipo1 ON (tipo1.pos = 1 AND pokemons.numero = tipo1.num_poke AND pokemons.forma = tipo1.num_forma) LEFT JOIN do_tipo as tipo2 ON (tipo2.pos = 2 AND pokemons.numero = tipo2.num_poke AND pokemons.forma = tipo2.num_forma) LEFT JOIN evolui_para ON(pokemons.numero = evolui_para.pre_evo_num AND pokemons.forma = evolui_para.pre_evo_forma) LEFT JOIN pokemons as evolucao ON (evolucao.numero = evolui_para.pos_evo_num AND evolucao.forma = evolui_para.pos_evo_forma) WHERE pokemons.nome = '"+nome+"';";
            var result = statement.executeQuery(query);
            result.next();
            txt_Pokemon.setText(result.getString("nome"));
            txt_n.setText(result.getString("numero"));
            int tamNome = nome.indexOf("-")+1;
            if (tamNome == 0){
                txt_f1.setText("original");
            } else{
                txt_f1.setText(result.getString("nome").substring(tamNome));
            }
            txt_f2.setText(result.getString("formato"));
            txt_c.setText(result.getString("cor"));
            tipo1 = result.getString("tipo_1");
            if (!(result.getString("tipo_2").equals("none"))){
                tipo2 = " e "+result.getString("tipo_2");
            }
            txt_t.setText(tipo1+tipo2);
            
            imagem = result.getBinaryStream("imagem");
            
            evolutions = result.getString("evo_nome");
            while (result.next()){
                evolutions = evolutions +", " +result.getString("evo_nome");
            }
            txt_e.setText(evolutions);
        } catch (SQLException ex){
            System.err.println(ex.getMessage());
        }
    }
    public void mostrarImagem(){
        
        try {
            // pega a imagem do banco de dados e abre uma frame com a imagem
            
            //InputStream is = rs.getBinaryStream("imagem");

            Image img = ImageIO.read(imagem);
            ImageIcon icon = new ImageIcon(img);
            JLabel label = new JLabel(icon);
            JFrame frame = new JFrame("Pokemon");
            frame.setSize(400, 400);
            frame.add(label);
            frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }

        // Exibir a imagem em um JLabel
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_Pokemon = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        bttn_imagem = new javax.swing.JButton();
        bttn_atq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_n = new javax.swing.JTextField();
        txt_t = new javax.swing.JTextField();
        txt_f1 = new javax.swing.JTextField();
        txt_f2 = new javax.swing.JTextField();
        txt_c = new javax.swing.JTextField();
        txt_e = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quem é esse pokemon?");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mini_pokebola_minimalista.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(98, 7, 7));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        txt_Pokemon.setEditable(false);
        txt_Pokemon.setBackground(new java.awt.Color(0, 0, 0));
        txt_Pokemon.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        txt_Pokemon.setForeground(new java.awt.Color(255, 255, 255));
        txt_Pokemon.setBorder(null);
        txt_Pokemon.setEnabled(false);
        txt_Pokemon.setFocusable(false);
        txt_Pokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PokemonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_Pokemon, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Pokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        bttn_imagem.setBackground(new java.awt.Color(204, 204, 204));
        bttn_imagem.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        bttn_imagem.setForeground(new java.awt.Color(0, 0, 0));
        bttn_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pokebola_minimalista.png"))); // NOI18N
        bttn_imagem.setText("Mostrar Pokemon");
        bttn_imagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_imagemActionPerformed(evt);
            }
        });

        bttn_atq.setBackground(new java.awt.Color(204, 204, 204));
        bttn_atq.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        bttn_atq.setForeground(new java.awt.Color(0, 0, 0));
        bttn_atq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pokebola_minimalista.png"))); // NOI18N
        bttn_atq.setText("Mostrar ataques");
        bttn_atq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_atqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttn_atq)
                    .addComponent(bttn_imagem))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bttn_imagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(bttn_atq)
                .addGap(65, 65, 65))
        );

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número:");

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo:");

        jLabel9.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Formato:");

        jLabel10.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cor:");

        jLabel11.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Evoluí para:");

        jLabel12.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Forma:");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N

        txt_n.setEditable(false);
        txt_n.setBackground(new java.awt.Color(98, 7, 7));
        txt_n.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_n.setForeground(new java.awt.Color(255, 255, 255));
        txt_n.setBorder(null);
        txt_n.setEnabled(false);
        txt_n.setFocusable(false);

        txt_t.setEditable(false);
        txt_t.setBackground(new java.awt.Color(98, 7, 7));
        txt_t.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_t.setForeground(new java.awt.Color(255, 255, 255));
        txt_t.setBorder(null);
        txt_t.setEnabled(false);
        txt_t.setFocusable(false);

        txt_f1.setEditable(false);
        txt_f1.setBackground(new java.awt.Color(98, 7, 7));
        txt_f1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_f1.setForeground(new java.awt.Color(255, 255, 255));
        txt_f1.setBorder(null);
        txt_f1.setEnabled(false);
        txt_f1.setFocusable(false);

        txt_f2.setEditable(false);
        txt_f2.setBackground(new java.awt.Color(98, 7, 7));
        txt_f2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_f2.setForeground(new java.awt.Color(255, 255, 255));
        txt_f2.setBorder(null);
        txt_f2.setEnabled(false);
        txt_f2.setFocusable(false);

        txt_c.setEditable(false);
        txt_c.setBackground(new java.awt.Color(98, 7, 7));
        txt_c.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_c.setForeground(new java.awt.Color(255, 255, 255));
        txt_c.setBorder(null);
        txt_c.setEnabled(false);
        txt_c.setFocusable(false);

        txt_e.setEditable(false);
        txt_e.setBackground(new java.awt.Color(98, 7, 7));
        txt_e.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_e.setForeground(new java.awt.Color(255, 255, 255));
        txt_e.setBorder(null);
        txt_e.setEnabled(false);
        txt_e.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txt_c))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_f2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txt_e))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_n)
                            .addComponent(txt_t)
                            .addComponent(txt_f1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_atqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_atqActionPerformed
        // abre tela de ataques do pokemon x
        new Tela_ataques(conn,nome).setVisible(true);
    }//GEN-LAST:event_bttn_atqActionPerformed

    private void bttn_imagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_imagemActionPerformed
        // chama o metodo de mostrar imagem
        mostrarImagem();
    }//GEN-LAST:event_bttn_imagemActionPerformed

    private void txt_PokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PokemonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_atq;
    private javax.swing.JButton bttn_imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_Pokemon;
    private javax.swing.JTextField txt_c;
    private javax.swing.JTextField txt_e;
    private javax.swing.JTextField txt_f1;
    private javax.swing.JTextField txt_f2;
    private javax.swing.JTextField txt_n;
    private javax.swing.JTextField txt_t;
    // End of variables declaration//GEN-END:variables
}
