/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author Gustavo Rinaldi
 */
public class Tela_ataques extends javax.swing.JFrame {

    Connection conn;
    String nome;
    /**
     * Creates new form Tela_ataques
     */
    public Tela_ataques(Connection conexao, String nome_p) {
        conn = conexao;
        nome = nome_p;
        initComponents();
        CarregarTipos();
        adicionarTabelaAtaques();
        txt_pokemon_name.setText(nome);
    }
    // adicionar os tipos na box, igual o da pokedex
    public void CarregarTipos(){
        tipo_filter.removeAllItems();
        tipo_filter.addItem("--");
        String query = "SELECT nome FROM tipos;";
        try{
            var cursor = conn.createStatement();
            var retorno = cursor.executeQuery(query);
            while (retorno.next()){
                tipo_filter.addItem(retorno.getString("nome"));
            }
        } catch (SQLException ex){
            System.err.println(ex.getMessage());
        }
    }
    public void adicionarTabelaAtaques(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome", "Tipo", "Poder", "Precisão"}, 0);
        // iterar pela lista completa de ataques do pokemon
        String query = "SELECT ataques.nome as nome, ataques.nome_tipo as tipo, ataques.accuracy as precisao, ataques.power as poder  FROM ataques, aprende_ataque, pokemons WHERE pokemons.nome = '"+nome+"' AND ataques.nome = aprende_ataque.nome_ataque AND pokemons.numero = aprende_ataque.num_poke AND pokemons.forma = aprende_ataque.num_forma;";
        try{
            var stmt = conn.createStatement();
            var result = stmt.executeQuery(query);
            while (result.next()){
                Object linha[] = new Object[]{result.getString("nome"), result.getString("tipo"), result.getString("poder"), result.getString("precisao")};
                modelo.addRow(linha);
            }
        } catch (SQLException ex){
            System.err.println("adicionarTabela: "+ex.getMessage());
        }
        
        tabela_ataques.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_pokemon_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_ataques = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tipo_filter = new javax.swing.JComboBox<>();
        bttn_search_tipo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nome_ataque = new javax.swing.JTextField();
        txt_forte = new javax.swing.JTextField();
        txt_fraco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_desc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de ataques");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mini_pokebola_minimalista.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(98, 7, 7));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pokebola_minimalista.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ataques do Pokemon");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pokemon: ");

        txt_pokemon_name.setEditable(false);
        txt_pokemon_name.setBackground(new java.awt.Color(98, 7, 7));
        txt_pokemon_name.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_pokemon_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_pokemon_name.setAutoscrolls(false);
        txt_pokemon_name.setBorder(null);
        txt_pokemon_name.setFocusable(false);
        txt_pokemon_name.setOpaque(true);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        tabela_ataques.setBackground(new java.awt.Color(0, 0, 0));
        tabela_ataques.setForeground(new java.awt.Color(255, 255, 255));
        tabela_ataques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Tipo", "Poder", "Precisão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_ataques.setShowGrid(true);
        tabela_ataques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_ataquesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_ataques);

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar tipo:");

        tipo_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bttn_search_tipo.setBackground(new java.awt.Color(204, 204, 204));
        bttn_search_tipo.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        bttn_search_tipo.setText("OK");
        bttn_search_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_search_tipoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Forte contra: ");

        jLabel7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fraco contra:");

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descrição: ");

        txt_nome_ataque.setEditable(false);
        txt_nome_ataque.setBackground(new java.awt.Color(98, 7, 7));
        txt_nome_ataque.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_nome_ataque.setForeground(new java.awt.Color(255, 255, 255));
        txt_nome_ataque.setBorder(null);
        txt_nome_ataque.setFocusable(false);

        txt_forte.setEditable(false);
        txt_forte.setBackground(new java.awt.Color(98, 7, 7));
        txt_forte.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_forte.setForeground(new java.awt.Color(255, 255, 255));
        txt_forte.setBorder(null);
        txt_forte.setFocusable(false);

        txt_fraco.setEditable(false);
        txt_fraco.setBackground(new java.awt.Color(98, 7, 7));
        txt_fraco.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txt_fraco.setForeground(new java.awt.Color(255, 255, 255));
        txt_fraco.setBorder(null);
        txt_fraco.setFocusable(false);

        txt_desc.setBackground(new java.awt.Color(98, 7, 7));
        txt_desc.setColumns(20);
        txt_desc.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txt_desc.setForeground(new java.awt.Color(255, 255, 255));
        txt_desc.setLineWrap(true);
        txt_desc.setRows(5);
        txt_desc.setWrapStyleWord(true);
        txt_desc.setBorder(null);
        jScrollPane2.setViewportView(txt_desc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tipo_filter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(bttn_search_tipo)
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nome_ataque))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_forte)
                                    .addComponent(txt_fraco)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pokemon_name, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_pokemon_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttn_search_tipo))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_nome_ataque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_forte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_fraco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_search_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_search_tipoActionPerformed
        if(tipo_filter.getSelectedItem().equals("--")){
            adicionarTabelaAtaques();
        }
        else{
            DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome", "Tipo", "Poder", "Precisão"}, 0);
            // iterar pela lista completa de ataques do pokemon
            String query = "SELECT ataques.nome as nome, ataques.nome_tipo as tipo, ataques.accuracy as precisao, ataques.power as poder  FROM ataques, aprende_ataque, pokemons WHERE pokemons.nome = '"+nome+"' AND ataques.nome = aprende_ataque.nome_ataque AND pokemons.numero = aprende_ataque.num_poke AND pokemons.forma = aprende_ataque.num_forma AND ataques.nome_tipo = '"+tipo_filter.getSelectedItem()+"';";
            try{
               var stmt = conn.createStatement();
                var result = stmt.executeQuery(query);
                while (result.next()){
                    Object linha[] = new Object[]{result.getString("nome"), result.getString("tipo"), result.getString("poder"), result.getString("precisao")};
                    modelo.addRow(linha);
                }
            } catch (SQLException ex){
                System.err.println("adicionarTabela: "+ex.getMessage());
            }
        
            tabela_ataques.setModel(modelo);
        }
    }//GEN-LAST:event_bttn_search_tipoActionPerformed

    private void tabela_ataquesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_ataquesMouseClicked
        // pega as informações do ataque x e preenche os txt
        // ****************************
        String atk_nom = tabela_ataques.getValueAt(tabela_ataques.getSelectedRow(),0).toString();
        // a row precisa ser maior q 0 e menor oiu igual ao numero de opções
        txt_nome_ataque.setText(atk_nom);
        String query = "SELECT texto, nome_tipo FROM ataques WHERE nome = '"+atk_nom+"';";
        String tipo = "";
        String fortes = "";
        String fracos = "";
        try{
            var stmt = conn.createStatement();
            var result = stmt.executeQuery(query);
            result.next();
            txt_desc.setText(result.getString("texto"));
            tipo = result.getString("nome_tipo");
            
        } catch (SQLException ex){
            System.err.println("texto: "+ex.getMessage());
        }
        try{
            query = "SELECT defensor FROM relacao_tipos WHERE atacante = '"+tipo+"' AND multiplicador > 1;";
            var stmt = conn.createStatement();
            var result = stmt.executeQuery(query);
            if (result.next()) {
                fortes = result.getString("defensor");
                while (result.next()){
                    fortes = fortes+", "+result.getString("defensor");
                }
            }
        } catch (SQLException ex){
            System.err.println("fortes: "+ex.getMessage());
        }
        try{
            query = "SELECT defensor FROM relacao_tipos WHERE atacante = '"+tipo+"' AND multiplicador < 1;";
            var stmt = conn.createStatement();
            var result = stmt.executeQuery(query);
            result.next();
            fracos = result.getString("defensor");
            while (result.next()){
                fracos = fracos+", "+result.getString("defensor");
            }
        } catch (SQLException ex){
            System.err.println("fracos: "+ex.getMessage());
        }
        txt_forte.setText(fortes);
        txt_fraco.setText(fracos);
    }//GEN-LAST:event_tabela_ataquesMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_search_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela_ataques;
    private javax.swing.JComboBox<String> tipo_filter;
    private javax.swing.JTextArea txt_desc;
    private javax.swing.JTextField txt_forte;
    private javax.swing.JTextField txt_fraco;
    private javax.swing.JTextField txt_nome_ataque;
    private javax.swing.JTextField txt_pokemon_name;
    // End of variables declaration//GEN-END:variables
}
