/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Gustavo Rinaldi
 */
public class Tela_cadastro_times extends javax.swing.JFrame {
    private Connection conn;
    /**
     * Creates new form Tela_cadastro
     */
    public Tela_cadastro_times(Connection conexao) {
        conn = conexao;
        initComponents();
        txt_nome_time.setEnabled(false);
        bttn_cria_time.setEnabled(false);
        CarregarTimes();
        CarregarStatus();
    }
     public void CarregarTimes(){
        times_box.removeAllItems();
        times_box.addItem("--");
        String query = "SELECT nome FROM equipes WHERE nome_dono = session_user;";
        try{
            var cursor = conn.createStatement();
            var retorno = cursor.executeQuery(query);
            while (retorno.next()){
                times_box.addItem(retorno.getString("nome"));;
            }
        } catch (SQLException ex){
            System.err.println(ex.getMessage());
        }
    }
    public void CarregarStatus(){
        status_box.removeAllItems();
        status_box.addItem("--");
        status_box.addItem("privado");
        status_box.addItem("público");
        status_box.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_nome_time = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bttn_cria_time = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        times_box = new javax.swing.JComboBox<>();
        bttn_confirma = new javax.swing.JButton();
        bttn_inicia_c = new javax.swing.JButton();
        status_box = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar novo treinador");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mini_pokebola_minimalista.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(98, 7, 7));

        txt_nome_time.setBackground(new java.awt.Color(153, 153, 153));
        txt_nome_time.setForeground(new java.awt.Color(0, 0, 0));
        txt_nome_time.setToolTipText("escolha uma senha ");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Gerenciamento de meus times");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pokebola_minimalista.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Abrir time:");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Nome do time:");

        bttn_cria_time.setBackground(new java.awt.Color(204, 204, 204));
        bttn_cria_time.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        bttn_cria_time.setForeground(new java.awt.Color(0, 0, 0));
        bttn_cria_time.setText("- Criar -");
        bttn_cria_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_cria_timeActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Criar time -");

        times_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bttn_confirma.setBackground(new java.awt.Color(204, 204, 204));
        bttn_confirma.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        bttn_confirma.setForeground(new java.awt.Color(0, 0, 0));
        bttn_confirma.setText("Confirma");
        bttn_confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_confirmaActionPerformed(evt);
            }
        });

        bttn_inicia_c.setBackground(new java.awt.Color(204, 204, 204));
        bttn_inicia_c.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        bttn_inicia_c.setForeground(new java.awt.Color(0, 0, 0));
        bttn_inicia_c.setText("criar");
        bttn_inicia_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_inicia_cActionPerformed(evt);
            }
        });

        status_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bttn_inicia_c)
                                .addGap(18, 18, 18)
                                .addComponent(status_box, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nome_time, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttn_cria_time)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(times_box, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttn_confirma)))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(times_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn_confirma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bttn_inicia_c)
                        .addComponent(status_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nome_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bttn_cria_time, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_cria_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_cria_timeActionPerformed
        if(txt_nome_time.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Escoha o nome para o seu time!", "Muitos pokemons... separe por nomes!", JOptionPane.ERROR_MESSAGE);
        }else{
            // cria o time e abre a tela do time
            // procedure insere_time
            String comando;
            if (status_box.getSelectedItem().equals("privado")){
                comando = "CALL insere_time('"+txt_nome_time.getText()+"',true);";
            } else {
                comando = "CALL insere_time('"+txt_nome_time.getText()+"',false);";
            }
            try{
                var cursor = conn.createStatement();
                var retorno = cursor.execute(comando);
                new Meu_time(conn,txt_nome_time.getText()).setVisible(true);
                CarregarTimes();
                CarregarStatus();
                txt_nome_time.setEnabled(false);
                txt_nome_time.setText("");
                bttn_cria_time.setEnabled(false);
                times_box.setEnabled(true);
                bttn_confirma.setEnabled(true);
                
            } catch (SQLException ex){
                System.err.println(ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_bttn_cria_timeActionPerformed

    private void bttn_confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_confirmaActionPerformed
        // pega o nome na box e abre a tela do time
        // Object time = times_box.getSelectedItem();
        if (times_box.getSelectedItem().equals("--")){
            JOptionPane.showMessageDialog(null, "Escolha um time.", "Alerta!", JOptionPane.ERROR_MESSAGE);
        } else{
            new Meu_time(conn,times_box.getSelectedItem().toString()).setVisible(true);
        }
    }//GEN-LAST:event_bttn_confirmaActionPerformed

    private void bttn_inicia_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_inicia_cActionPerformed
        txt_nome_time.setEnabled(true);
        txt_nome_time.requestFocus(true);
        bttn_cria_time.setEnabled(true);
        times_box.setEnabled(false);
        bttn_confirma.setEnabled(false);
        status_box.setEnabled(true);
    }//GEN-LAST:event_bttn_inicia_cActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_confirma;
    private javax.swing.JButton bttn_cria_time;
    private javax.swing.JButton bttn_inicia_c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> status_box;
    private javax.swing.JComboBox<String> times_box;
    private javax.swing.JTextField txt_nome_time;
    // End of variables declaration//GEN-END:variables
}
